### ISSUE TITLE
`samples` field is truncated in deletion, substitution .csvs

### ISSUE THREAD

**Issue by flaneuse** [andersen-lab/HCoV-19-Genomics#9]
just as an FYI... export coalesces the sample names in the middle to `...` in the substitution .csv and truncates the list in the deletion one before the list is complete.  

NBD, just letting you know @AlaaALatif.

https://github.com/andersen-lab/HCoV-19-Genomics/tree/master/variants

**Comment by AlaaALatif** [comment]
Hi @flaneuse , that was not the intended behavior. Apologies for the mishap and thanks alot for raising the issue. I just pushed a potential fix where sample names are stored as comma-separated strings. I have also applied the same change to all "list-like" fields in order to prevent truncation from happening in any of them in the future. 

The tables have also been updated based on most recent data from A-lab and GISAID.

Thanks again and please let me know if there's anything else
